### ISSUE TITLE
SIARDDK can't handle bit varying

### ISSUE THREAD

**Issue by PhillipTommerholt** [keeps/db-preservation-toolkit#250]
This is so far not a pilot blocker.

When trying to export to SIARDDK from MS SQL Server, DBPTK stops the export process when it meets the data type BIT VARYING. 

There are BIT VARYING in system tables. Se for example Northwind. System tables are not preserved in DK but there might be data types in "the real" tables. In AdventureWorks2012 there are datatypes in the tables that SIARDDK can't handle. 

I am going to a pilot site the 23rd of August. I don't know if this datatype is present in the database.

**Comment by PhillipTommerholt** [comment]
This is now a pilot blocker.

**Comment by andreaskring** [comment]
@PhillipTommerholt There is a problem with the BIT VARYING datatype since it is not supported in the import phase of the DB extraction. I have tried exporting data from a PostgreSQL DB containing a table with a BIT VARYING column, and I get this error:

`2016-09-12 12:32:09,715 [main] DEBUG (c.d.m.j.i.JDBCDatatypeImporter) Unsupported JDBC type, code: 1111
2016-09-12 12:32:09,715 [main] DEBUG (c.d.m.Reporter) customMessage, invoker: com.databasepreservation.modules.postgreSql.in.PostgreSQLJDBCDatatypeImporter; message: - Possibility of incomplete type definition: Could not determine SQL99 type for varbit
2016-09-12 12:32:09,715 [main] DEBUG (c.d.m.Reporter) customMessage, invoker: com.databasepreservation.modules.postgreSql.in.PostgreSQLJDBCDatatypeImporter; message: - Possibility of incomplete type definition: Could not determine SQL2008 type for varbit
2016-09-12 12:32:09,715 [main] DEBUG (c.d.m.j.i.JDBCImportModule) Closing connection to source database
2016-09-12 12:32:09,715 [main] ERROR (c.d.Main) Fatal error: Unexpected exception (null)
java.lang.NullPointerException: null
        at com.databasepreservation.model.Reporter.dataTypeChangedOnImport(Reporter.java:253)
        at com.databasepreservation.model.modules.DatatypeImporter.checkType(DatatypeImporter.java:97)
        at com.databasepreservation.model.modules.DatatypeImporter.getCheckedType(DatatypeImporter.java:71)
        at com.databasepreservation.modules.jdbc.in.JDBCImportModule.getColumn(JDBCImportModule.java:803)
        at com.databasepreservation.modules.jdbc.in.JDBCImportModule.getColumns(JDBCImportModule.java:701)
        at com.databasepreservation.modules.jdbc.in.JDBCImportModule.getTableStructure(JDBCImportModule.java:504)
        at com.databasepreservation.modules.jdbc.in.JDBCImportModule.getTables(JDBCImportModule.java:425)
        at com.databasepreservation.modules.jdbc.in.JDBCImportModule.getSchemaStructure(JDBCImportModule.java:302)
        at com.databasepreservation.modules.jdbc.in.JDBCImportModule.getSchemas(JDBCImportModule.java:269)
        at com.databasepreservation.modules.jdbc.in.JDBCImportModule.getDatabaseStructure(JDBCImportModule.java:220)
        at com.databasepreservation.modules.jdbc.in.JDBCImportModule.getDatabase(JDBCImportModule.java:1493)
        at com.databasepreservation.Main.run(Main.java:127)
        at com.databasepreservation.Main.internal_main(Main.java:80)
        at com.databasepreservation.Main.main(Main.java:62)
`
@chalkos Could you please take a look at this?

**Comment by chalkos** [comment]
@andreaskring This seems to be a type that had not shown up until now. Handling it should be trivial, because we already have bit varying handling, I just need to specify that JDBC type 1111 should use bit varying

**Comment by chalkos** [comment]
I noticed that @PhillipTommerholt is using MSSQLServer and @andreaskring is using PostgreSQL.
Is this correct?

**Comment by PhillipTommerholt** [comment]
For my side: yes.

**Comment by chalkos** [comment]
@PhillipTommerholt are you able to export the same database to SIARD2?

**Comment by PhillipTommerholt** [comment]
>  @PhillipTommerholt are you able to export the same database to SIARD2?

Yes.

**Comment by andreaskring** [comment]
@chalkos I have just tried to export from PostgreSQL to SIARD 2.0, and I still get the same error, so I think there must be a problem with the PostgreSQL import module. Do you mind trying to create this table in PostGreSQL and then try to export it to SIARD 2.0?:

`$ create table bitVarying (id int primary key, b BIT VARYING(5));`
`$ insert into bitvarying values (0,B'101');`

Maybe we could have a short talk about thsi over Skype?

**Comment by chalkos** [comment]
@andreaskring I agree that there is a problem with PostgreSQL import. But I'm not sure that it is related to the issue @PhillipTommerholt described...

I will try to test that today with PostgreSQL, although I think that it is a different issue. After I look into this the skype chat might be useful.

@andreaskring are you able to test with MS SQL Server and database AdventureWorks2012?
Phillip said that is has the problematic data types.

**Comment by andreaskring** [comment]
@chalkos Ok - thanks. I have added the necessary SIARDDK export module changes for handling the BIT VARYING datatype. I will build a jar for Phillip an ask him to test againts MSSQL - @PhillipTommerholt is this ok with you?

**Comment by PhillipTommerholt** [comment]
Yes, splendid.

**Comment by chalkos** [comment]
@PhillipTommerholt @andreaskring what is the status on this? it would be great to have this fix included in beta6

**Comment by PhillipTommerholt** [comment]
I can give you an answer within a couple of hours.

**Comment by chalkos** [comment]
(I removed the MSSQLServer label since @PhillipTommerholt already confirmed that the problem does not happen when converting to SIARD 2, so the MS SQL module is behaving correctly)

**Comment by PhillipTommerholt** [comment]
I tested with the jar you sent me @andreaskring but it fails.
The log mentions the specific column which is problematic. The specific datatype is `BIT VARYING(50)` a valid variant of `BIT VARYING`.

**Comment by andreaskring** [comment]
@PhillipTommerholt Ok - I will have another look at this when issue #265 has been resolved. In that way it will be easier for me to debug since I can try exporting a PostgreSQL DB containing BIT VARYING

**Comment by chalkos** [comment]
@andreaskring that is a totally unrelated issue that is related to the (bad) way PortgreSQL JDBC Driver handles binary types. I would be very surprised if it influenced MS SQL Server import module in any way.

Why do you need to export a PostgreSQL DB containing BIT VARYING? I'm curious as to how that would help debug the existing problem in MS SQL Server...

**Comment by andreaskring** [comment]
@chalkos Maybe I understand the problem incorrectly... in my understanding the problem right now is in the SIARDDK export module since it is possible to export to SIARD 2.0. For convenience, when working with the export side of the code, it would be nice to be able to export from a DB supporting BIT VARYING (I have access to PostgreSQL and MySQL (and the latter does not support BIT VARYING)). So if I could use a PostgreSQL DB containing BIT VARYING, I could use that to make sure that the SIARDDK export module handles this (and thereby BIT VARYING) correctly.

I could also generate a mock DatabaseStructure and use this, but in the other way, i could test the whole process from a real DB containing BIT VARYING to SIARDDK. Or do you suggest doing it differently?

**Comment by chalkos** [comment]
Ok, now I understand your perspective.

I am looking into #265 and it will be handled differently. You could try to use a vagrant or docker machine to try the AdventureWorks2012 database.

**Comment by chalkos** [comment]
#265 is now fixed in master branch

**Comment by andreaskring** [comment]
Great - thanks. I will continue on this issue

**Comment by andreaskring** [comment]
The necessary changes have been made and @PhillipTommerholt is currently testing these

**Comment by PhillipTommerholt** [comment]
It still throws a fatal error in the export on the same column.
Instead of bit varying it now states that the same column is binary varying.

[BINARYVARYING.txt](https://github.com/keeps/db-preservation-toolkit/files/502204/BINARYVARYING.txt)

**Comment by chalkos** [comment]
@andreaskring try using this https://atlas.hashicorp.com/msabramo/boxes/mssqlserver2014express

It may take a while to set up the server, but once set up it will be a lot easier to debug the problem. And it will probably be faster than playing cat and mouse with the bug.

**Comment by andreaskring** [comment]
The necessary changes have been made and @PhillipTommerholt has tested these. The issue it fixed, so I will merge the changes into pull request #261
